# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 导航菜单
menu:
  首页   : / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  娱乐 ||fa fa-heartbeat:
    音乐: /music/ || fas fa-music
    图库: /gallery/ || fas fa-images
    电影: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart


#渲染方式 highlight和prismjs
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
# 高亮主题
highlight_theme: darker
# 代码复制
highlight_copy: true
#代码框是否展开
highlight_shrink: false #代碼框展開，需點擊 '>' 打開
code_word_wrap: true #代碼框自动换行
highlight_height_limit: false # unit: px
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''
# 社交图标
social:
  fab fa-github: https://github.com/shadowofgost || Github
  fas fa-envelope: mailto:shadowofgost@outlook.com || Email
# 主页文章自动展示
index_post_content:
  method: 2
  length: 200 # if you set method to 2 or 3, the length need to config

# 顶部图片配置
# 主页的top_img
index_img: https://i.loli.net/2019/11/10/T7Mu8Aod3egmC4Q.png
# 默認的 top_img，當頁面的 top_img 沒有配置時，會顯示 default_top_img
default_top_img: https://i.loli.net/2019/11/10/T7Mu8Aod3egmC4Q.png
# 歸檔頁面的 top_img
archive_img: https://i.loli.net/2019/11/10/T7Mu8Aod3egmC4Q.png
# tag 子頁面 的 默認 top_img
tag_img: https://i.loli.net/2019/11/10/T7Mu8Aod3egmC4Q.png
# tag 子頁面的 top_img，可配置每個 tag 的 top_img
tag_per_img: https://i.loli.net/2019/11/10/T7Mu8Aod3egmC4Q.png
# category 子頁面 的 默認 top_img
category_img: https://i.loli.net/2019/11/10/T7Mu8Aod3egmC4Q.png
# category 子頁面的 top_img，可配置每個 category 的 top_img
category_per_img: https://i.loli.net/2019/11/10/T7Mu8Aod3egmC4Q.png
## img的值配置
# 留空	顯示默認的top_img（如有），否則顯示默認的顔色
#（文章頁top_img留空的話，會顯示 cover 的值）
# img鏈接	效果圖片的鏈接，顯示所配置的圖片
# 顔色(HEX值 - #0000FFRGB值 - rgb(0,0,255)顔色單詞 - orange漸變色 - linear-gradient( 135deg, #E2B0FF 10%, #9F44D3 100%)）	對應的顔色
# transparent	透明
# false	不顯示 top_img
# 网站背景配置
# 圖片格式 url(http://xxxxxx.com/xxx.jpg)
# 顏色（HEX值/RGB值/顔色單詞/漸變色)
# 留空 不顯示背景
background:


# footer是否顯示圖片背景(與top_img一致)
footer_bg: true
# 留空/false	顯示默認的顔色
# img鏈接	圖片的鏈接，顯示所配置的圖片
# 顔色(HEX值 - #0000FFRGB值 - rgb(0,0,255)顔色單詞 - orange漸變色 - linear-gradient( 135deg, #E2B0FF 10%, #9F44D3 100%)）	對應的顔色
# true	顯示跟 top_img 一樣

# 文章封面展示
cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: right
  # 當沒有設置cover時，默認的封面顯示
  default_cover:
    - https://i.loli.net/2019/11/10/T7Mu8Aod3egmC4Q.png
    - https://i.loli.net/2019/12/25/8t97aVlp4hgyBGu.jpg
    - https://i.loli.net/2019/12/25/hOqbQ3BIwa6KWpo.jpg

# 文章页的相关配置
post_meta:
 # 主页的相关配置
  page:
    date_type: both # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  # 文章页的相关配置
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字

# 文章版权的配置
post_copyright:
  enable: true
  decode: true
  author_href: https://github.com/shadowofgost
  license: CC BY-NC-ND 4.0
  license_url: https://creativecommons.org/licenses/by-nc-nd/4.0

# 文章打赏配置
reward:
  enable: true
  QR_code:
    - img: /img/weichat.jpg
      link:
      text: 微信
    - img: /img/alipay.jpg
      link:
      text: 支付宝

# 文章概要
toc:
  post: true #文章頁是否顯示 TOC
  page: false # 普通頁面是否顯示 TOC
  number: true # 是否顯示章節數
  expand: false # 是否展開 TOC
  style_simple: false # for post 簡潔模式（側邊欄只顯示 TOC, 只對文章頁有效 ）
# 相关文章推荐
related_post:
  enable: true
  limit: 4 # 顯示推薦文章數目
  date_type: updated # or created or updated 文章日期顯示創建日或者更新日

# anchor 文章锚点
# when you scroll in post , the url will update according to header id.
anchor: true

# Displays outdated notice for a post (文章過期提醒)
noticeOutdate:
  enable: true
  style: flat # style: simple/flat
  limit_day: 365 # When will it be shown
  position: top # position: top/bottom
  message_prev: It has been
  message_next: days since the last update, the content of the article may be outdated.

# Post edit 文章编辑按钮
# Easily browse and edit blog source code online.
post_edit:
  enable: false
  # url: https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name/
  # For example: https://github.com/jerryc127/butterfly.js.org/edit/main/source/
  url:

# 头像处理
avatar:
  img: /img/main.jpg
  effect: false # 頭像會一直轉圈

# 图片描述
photofigcaption: true

# 文章复制控制
# copy settings
# copyright: Add the copyright information after copied content (複製的內容後面加上版權信息)
copy:
  enable: true # 是否開啟網站複製權限
  copyright: # 複製的內容後面加上版權信息
    enable: true # 是否開啟複製版權信息添加
    limit_count: 25 # 複製的內容最多字數

# 博客年份设置
footer:
  owner:
    enable: true
    since: 2022

# footer自定义
custom_text: <a href="icp鏈接"><img class="icp-icon" src="icp圖片"><span>備案號：xxxxxx</span></a>

# 转换
translate:
  enable: true
  # 默認按鈕顯示文字(網站是簡體，應設置為'default: 繁')
  default: 简
  #網站默認語言，1: 繁體中文, 2: 簡體中文
  defaultEncoding: 2
  #延遲時間,若不在前, 要設定延遲翻譯時間, 如100表示100ms,默認為0
  translateDelay: 0
  #當文字是簡體時，按鈕顯示的文字
  msgToTraditionalChinese: "繁"
  #當文字是繁體時，按鈕顯示的文字
  msgToSimplifiedChinese: "简"

# 夜间模式
# dark mode
darkmode:
  enable: true
  # dark mode和 light mode切換按鈕
  button: true
  autoChangeMode: false
# 阅读模式
readmode: true
# 按钮排序
# Don't modify the following settings unless you know how they work (非必要請不要修改 )
# Choose: readmode,translate,darkmode,hideAside,toc,chat,comment
# Don't repeat 不要重複
rightside_item_order:
  enable: true
  hide: # readmode,translate,darkmode,hideAside
  show: toc,chat,comment,readmode,translate,darkmode,hideAside
# 侧边设置
aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手機頁面（ 顯示寬度 < 768px ）是否顯示aside內容
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Github
      link: https://github.com/jerryc127/hexo-theme-butterfly
  card_announcement:
    enable: true
    content: This is my Blog
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true



# 访问人数
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 运行时间
runtimeshow:
  enable: true
  publish_date: 2022/07/11 00:00:00
  ##網頁開通時間
  #格式: 月/日/年 時間
  #也可以寫成 年/月/日 時間

# mermaid
# see https://github.com/mermaid-js/mermaid
mermaid:
  enable: true
  # built-in themes: default/forest/dark/neutral
  theme:
    light: default
    dark: dark

# 搜索设置
algolia:
  chunkSize: 5000
  indexName: "my-hexo-blog"
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - images
    - slug
    - tags
    - title

# 网站搜录验证
# site_verification:
  # - name: google_site_verification
  #   content: xxxxxx
  # - name: baidu_site_verification
  #   content: xxxxxxx
# 数学渲染使用
mathjax:
  enable: false
  # true 表示每一頁都加載mathjax.js
  # false 需要時加載，須在使用的Markdown Front-matter 加上 mathjax: true
  per_page: false
# kramed的配置文件
katex:
  enable: true
  # true 表示每一頁都加載katex.js
  # false 需要時加載，須在使用的Markdown Front-matter 加上 katex: true
  per_page: false
  hide_scrollbar: true

# 打字效果
# Typewriter Effect (打字效果)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (冒光特效)
  shake: true #  open shake (抖動特效)
  mobile: false

# 页面美化
# 美化頁面顯示
beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"
# 页面加载
# 加載動畫 Loading Animation
preloader: true
# PWA 配置
# 后续补充
pwa:
  enable: true
  manifest: /manifest.json
  apple_touch_icon: /img/icon.png
  favicon_32_32: /img/icon.png
  favicon_16_16: /img/icon.png
  mask_icon: /img/icon.png


# 字数统计
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# 图片大图查看模式
# fancybox http://fancyapps.com/fancybox/3/
fancybox: true
# A simple 404 page
error_404:
  enable: true
  subtitle: "頁面沒有找到"
  background:

# snackbar 弹窗
# Snackbar 彈窗
# https://github.com/polonel/SnackBar
# position 彈窗位置
# 可選 top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
snackbar:
  enable: true
  position: bottom-left
  bg_light: '#49b1f5' #light mode時彈窗背景
  bg_dark: '#2d3035' #dark mode時彈窗背景

# css前缀提高兼容性
# Add the vendor prefixes to ensure compatibility
css_prefix: true
# open graph 优化
# Open graph meta tags
# https://developers.facebook.com/docs/sharing/webmasters/
Open_Graph_meta: true
# instantpage 提高预加载优化
# https://instant.page/
# prefetch (預加載)
instantpage: true
# 中英文混杂
# https://github.com/vinta/pangu.js
# Insert a space between Chinese character and English character (中英文之間添加空格)
pangu:
  enable: true
  field: site # site/post
# ajax优化提高加载速度
# Pjax [Beta]
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
pjax:
  enable: true
  exclude:
    - /music/
    - /no-pjax/

# sitemap SEO优化
# 自动生成sitemap
sitemap:
  path: sitemap.xml
# 文件压缩
# 开启压缩
neat_enable: true
neat_html:
  enable: true
  exclude:
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/index.js'
